name: "upload_sarif"

# Run workflow each time code is pushed to your repository and on a schedule.
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Scan repository
      #   uses: MeterianHQ/meterian-github-action@v1.0.13
      #   env: 
      #      METERIAN_API_TOKEN: ${{secrets.METERIAN_API_TOKEN}}
      #      CLIENT_CANARY_FLAG: "--canary"
      #   with:
      #      cli_args: "--report-sarif=report.sarif"

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: report.sarif

